config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'welcome/index'
  get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :users
	#root 'welcome#index'
  root 'sessions#new'

	get '/signup', to: 'users#new'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 100},
		format: {with: VALID_EMAIL_REGEX}, uniqueness: true

	has_secure_password
	validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])

  	if user and user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
		  flash[:danger] = 'Invalid email/password combination'
    	render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)

    if @user.save
      log_in @user
      #flash.now[:success] = "Welcome to Scuben Corp!"
    	redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#Log in a user
	def log_in(user)
		session[:user_id] = user.id
	end

	# Returns current logged in user, if any
	def current_user
		if session[:user_id]
			@current_user = @current_user ||
			User.find_by(id: session[:user_id])
		end
	end

	# Returns boolean of a user login status
	def logged_in?
		!current_user.nil?
	end

	#invalidates the session, logging out the user
	def log_out
		session.delete(:user_id)
		@current_user= nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SCUBEN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h2>User Sign Up</h2>

<% if @user.errors.any? %>
  <div">
    <div>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
<br/>
      <%= f.label :email %>
      <%= f.email_field :email %>
<br/>
	  <%= f.label :password %>
      <%= f.password_field :password %>
<br/>
     <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
<br/>
      <%= f.submit "Create my account"%>
    <% end %>
  </div>
  

app/views/users/show.html.erb
<% if logged_in? %>

  <strong>Hi, <%= @user.name.capitalize %> </strong>

  <h4>S-CUBE-N Corp. offers you the following range of services </h4>
  <%= link_to "Banking", '#' %>
  <br/>
  <%= link_to "Make Investments", '#' %>
  <br/>
  <%= link_to "Buy Insurance", '#' %>
  <br/>
  <br/>
  <br/>
  <br/>
	<%= link_to "Log out", logout_path, method: :delete %>
<% else %>
	<%= link_to "Log In", login_path %>
<% end %>

app/views/welcome/index.html.erb
<!DOCYTPE html>
<html>
<header>
<h1 align="center">SCUBEN Bankers</h1>
</header>
<body>

<p> If you are a first-time user, sign up to get started...
<%= link_to "Sign Up", signup_path %>
</p>

<p> If you are already our customer, please log in....
<%= link_to "Log In", login_path %>
</p>

</body>
</html>